import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EmulatorFrame from "@/components/ui/emulator-frame";
import { headers } from "next/headers";
import { isMobileUserAgent } from "@/lib/ua-detection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Server-side user agent detection
  const userAgent = (await headers()).get("user-agent") || "";

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Pangolin"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen bg-black h-screen flex items-center justify-center">
          <EmulatorFrame isMobile={isMobileUserAgent(userAgent)}>
            <div className="max-w-[var(--virtual-screen-max-width)] h-full max-h-[700px] mx-auto w-full bg-white overflow-hidden">
              {children}
            </div>
          </EmulatorFrame>
        </div>
      </body>
    </html>
  );
}
